### ISSUE TITLE
Issues with 'truncate-lines nil (Wrap at window edge)

### ISSUE THREAD

**Issue by MLopez-Ibanez** [alpaker/fill-column-indicator#26]
I know the instructions warn that Fill-Column-Indicator doesn't work reliably with 'truncate-lines nil, but 'truncate-lines nil is the default and for long lines, it is a pain to not be able to read all text without horizontal scrolling, so it would be desirable if it worked out-of-the-box. 

Here http://www.emacswiki.org/emacs/FillColumnIndicator there is a work-around:

<pre>
(setq-default fci-rule-column 80)
(setq fci-handle-truncate-lines nil)
(add-hook 'after-change-major-mode-hook 'auto-fci-mode)
(add-hook 'window-size-change-functions 'auto-fci-mode)

(defun auto-fci-mode (&optional unused)
  (if (> (frame-width) 80)
      (fci-mode 1)
    (fci-mode 0))
)
</pre>

The above hack works fairly well, but it fails if I open two files at the same time: emacs test.c test2.c then, the first buffer will have the fill-column-marker, even if the size of the window is less than 80 columns.

Would you accept patches adding this feature?

**Comment by aspiers** [comment]
@MLopez-Ibanez Please can you [submit your patch as a pull request](https://help.github.com/articles/using-pull-requests/)?  It's exactly what they were designed for, whereas pasting patches as comments a) makes the issues unnecessarily long and b) makes it very hard to test or review or keep track of the patches.  Thanks.

**Comment by aspiers** [comment]
@MLopez-Ibanez I just tried your patch and it does seem to work and get rid of the fringe indicators.  But as mentioned it's unusable for a lot of people when provided as a patch in a comment.

**Comment by MLopez-Ibanez** [comment]
If you tell me the git command to do it, I'll try next time that I have 15
mins free. Thanks.

**Comment by aspiers** [comment]
@MLopez-Ibanez The info is in the link I already sent you.  There are lots of other guides too if you google for "github pull request".

**Comment by MLopez-Ibanez** [comment]
Done. I hope it is useful.

**Comment by alpaker** [comment]
Thanks very much @MLopez-Ibanez.  I'll have a look in the morning.

**Comment by alpaker** [comment]
Just FYI, I'm abandoning this package and welcoming requests to be take over as maintainer.

**Comment by alpaker** [comment]
The functionality provided by this package has now been implemented natively in Emacs as `display-fill-column-indicator-mode`, available as of version 27.0.90. Unless you are forced to use an older Emacs, you should use the native implementation instead of `fci-mode`. The former is unaffected by most of the compatibility issues that this add-on has.
