### ISSUE TITLE
Emacs 24.3 previous-line on empty line moves pointer up two lines

### ISSUE THREAD

**Issue by imfranklin** [alpaker/fill-column-indicator#31]
With version 1.84 in Emacs 24.3 on Mac OS X 10.8.3 previous-line (via <up> or C-p) on an empty line moves the pointer up twice (to the previous, previous line).

**Comment by joncol** [comment]
Good stuff remvee. Your fix caused some problems when standing on line #1. Small fix:

    (make-variable-buffer-local 'line-move-visual)
    (defadvice previous-line (around avoid-jumpy-fci activate)
      (if (and (symbol-value 'fci-mode) (> (count-lines 1 (point)) 0))
          (prog (fci-mode -1) ad-do-it (fci-mode 1))
        ad-do-it))

**Comment by djs52** [comment]
For anyone who needs this fix still (e.g., if you are on Ubuntu 14.04), "prog" should be "progn", so:

```elisp
(make-variable-buffer-local 'line-move-visual)
(defadvice previous-line (around avoid-jumpy-fci activate)
  (if (and (symbol-value 'fci-mode) (> (count-lines 1 (point)) 0))
      (progn (fci-mode -1) ad-do-it (fci-mode 1))
    ad-do-it))
    ```

**Comment by qrilka** [comment]
Shouldn't this issue be removed from the README?
