### ISSUE TITLE
fill column indicator causes arrow fringe indicators on every line.

### ISSUE THREAD

**Issue by joe9** [alpaker/fill-column-indicator#44]
Hello,

This is how it looks without fill-column-indicator:
![2014-03-01-194834_2960x1050_scrot](https://f.cloud.github.com/assets/1084520/2303245/c0805486-a1ad-11e3-8232-3dd765a67610.png)

This is how it looks with fill-column-indicator (every line ending has an arrow fringe indicator)
![2014-03-01-194911_2960x1050_scrot](https://f.cloud.github.com/assets/1084520/2303246/cae6fa42-a1ad-11e3-8c17-c3d3718c3d0b.png)

This is the code I am using to enable fill-column-indicator.
(require 'fill-column-indicator)
(define-globalized-minor-mode global-fci-mode fci-mode fci-mode)
(setq fci-rule-color "darkred")
(global-fci-mode)
;; (fci-mode)

Just wanted to check if this is fixable.

Thanks
Joe

**Comment by felixSchl** [comment]
Has there been any movement on this?

**Comment by alpaker** [comment]
This is going to require adding a new feature in the C-level display
routine in Emacs proper.  I had something working last year, but it's been
on the shelf since then.

Realistically, I don't know when I'll be able to get around to this.

**Comment by aspiers** [comment]
@alpaker Perhaps you would consider allowing sometime to act as co-maintainer whilst you are too busy to fix things?

**Comment by ideasman42** [comment]
Also running into this, [heres a workaround](http://emacs.stackexchange.com/a/29125/2418) that disables fci when its not visible.

**Comment by alpaker** [comment]
Just FYI, I'm abandoning this package and welcoming requests to be take over as maintainer.

**Comment by alpaker** [comment]
The functionality provided by this package has now been implemented natively in Emacs as `display-fill-column-indicator-mode`, available as of version 27.0.90. Unless you are forced to use an older Emacs, you should use the native implementation instead of `fci-mode`. The former is unaffected by most of the compatibility issues that this add-on has.
