### ISSUE TITLE
Enable by default?

### ISSUE THREAD

**Issue by JuanCaicedo** [alpaker/Fill-Column-Indicator#65]
My apologies if this isn't the best place to ask this.

I was able to install the package and I can get it to work by running `fci-mode`. Is there a way to enable this by default? That is, I want to get FCI on all files without having to turn it on. 

I could make a PR to add this to the documentation afterwards.

**Comment by hmehra** [comment]
Put this in your init file:

(add-hook 'after-change-major-mode-hook 'fci-mode)

**Comment by JuanCaicedo** [comment]
Thanks @hmehra~ I wasn't able to get that to work, but it got me to try the following which did:
```lisp
 (add-hook 'change-major-mode-after-body-hook 'fci-mode)
```
Maybe it's because of the distribution I'm using? I'm using [spacemacs](https://github.com/syl20bnr/spacemacs), which runs it's own init that you configure from a different file.
