### ISSUE TITLE
Provide face instead of `fci-rule-color`, for easy theming

### ISSUE THREAD

**Issue by viccuad** [alpaker/Fill-Column-Indicator#66]
Hi,

Is it possible to provide a face that Fill-Column-Indicator can use, instead
of the current var, so color themes can set it easily?

(Maybe I'm asking something silly, as my elisp-fu is limited).

Cheers.

**Comment by ryuslash** [comment]
Themes can already easily set this color:

```
(custom-theme-set-variables 'THEME-NAME '(fci-rule-color "#800000"))
```

I hope this helps.

**Comment by alpaker** [comment]
The color is used to create a bitmap image.  Faces can't be used for that:  We need to create a string containing the data for a PBM or XPM image with the color explicitly represented as an RGB value. 

Sorry!
