### ISSUE TITLE
Breaks magit-status buffer

### ISSUE THREAD

**Issue by aspiers** [alpaker/fill-column-indicator#69]
If I jump to an unstaged or staged change in the magit status buffer, and press `4` to expand it, it sometimes behaves as if the point was on the line above, prior to expanding.  If I then run `M-x fci-mode` to disable it, magit starts behaving perfectly.

~~Unfortunately there doesn't seem to be any way to permanently turn fci off for magit status buffers, as per #68.~~

**Comment by aspiers** [comment]
I haven't seen this problem in a long time so presumably it got fixed somehow.

**Comment by aspiers** [comment]
Wow, that's weird - all of a sudden I'm seeing it again.  But maybe only on deleted files?

**Comment by alpaker** [comment]
Thanks for the report.  I'll try to take a look later this week but, to be honest, I'm barely doing work on this package.  (I think the mechanism the mode uses is fundamentally unsuited to the purpose; it needs to be reimplemented some other way.)

**Comment by alpaker** [comment]
Just FYI, I'm abandoning this package and welcoming requests to be take over as maintainer.

**Comment by x-yuri** [comment]
I think these are safer defaults (enable only on buffers visiting files, you don't really need `fci-mode` for `magit` buffers, are you?):

```lisp
  (require 'fill-column-indicator)
  (define-globalized-minor-mode global-fci-mode fci-mode
    (lambda ()
      (if buffer-file-name (fci-mode 1))))
  (global-fci-mode 1)
```

On a side note, I'm still curious what's going on here. Let's say you've got 2 modified files, each with a hunk:

![](https://i.imgur.com/8aA3AhC.png)

You put the cursor on the second one (modified b, column 0):

![](https://i.imgur.com/HSdBTCL.png)

But with `fci-mode` you're indeed at the beginning of the first hidden line before the current one (the first line of the hidden hunk of the first file). As such, `magit` thinks, "I'm at the hunk of the first file," and toggles it, not the second file.

**Comment by alpaker** [comment]
Honestly, I'm not sure this is worth investigating.`fci-mode` works, to the extent that it does, by using the APIs provided Emacs's display engine in ways they weren't designed for, which causes all kinds of unexpected interaction with other packages that manipulate buffer display. I don't think there's any way to make the current implementation play well in general with other display features.

But there's no need to deal with these hassles. The functionality provided by `fci-mode` has been implemented natively in Emacs core as `display-fill-column-indicator-mode`, available in Emacs 27. Unless you're forced to use an older version some reason, you should just use the native implementation, which should be robust to all these issues.

**Comment by x-yuri** [comment]
Good point about "implemented natively", I was going to say. But then I looked, and saw that Emacs 27 [hasn't supposedly yet been released][1]. On the other hand, fixing it here indeed makes not much sense.

I rather was basically curious what's going on. And today I've figured it out. The thing that breaks `magit` is `line-move-visual` set to `nil`. That is you don't need `fci`, open `magit-status`, do `(setq line-move-visual nil)`, and you get the same (mis)behavior. It's not like it doesn't work at all. With my color theme the lines are generally highlighted. If you happen on a line that isn't, it's not gonna expand (not in a meaningful way). But you can move the cursor right a couple of times (2 times to be precise), it gets highlighted, and starts working.

Also, just yesterday I realized that you might want a column indicator in a `magit-status` buffer. So, either install Emacs 27, or bear with this (mis)behavior, or disable for `magit` buffers.

[1]: https://www.gnu.org/software/emacs/

**Comment by alpaker** [comment]
Ah, sorry, I thought I saw the release announcement, but it was only an announcement of the release candidate. It's imminent, at least. 

Thanks for tracking the cause down.  At the time I first implemented `fci-mode`, cursor motion behaved erratically when `line-move-visual` was enabled.  Perhaps the issues have been smoothed out since.
