### ISSUE TITLE
New Emacs 26 display-line-numbers breaks Fill-Column-Indicator

### ISSUE THREAD

**Issue by naclander** [alpaker/Fill-Column-Indicator#78]
Emacs 26 has added its own built-in line numbering system that obsoletes (n)linum.

This seems incompatible with FCI. When both FCI is enabled and `setq display-line-numbers t` is set the line numbering essentially look like:

```
1| Some text         |
2| Some more text    |
3| Some more text    |
4| A line with very very long text |
5| Some more text    |
```

Where the bar on the right represents the FCI line. The Emacs built-in line numbering is the now recommended way to display line numbering, and it has essentially deprecated (n)linum mode, so I think it would be a good idea to make FCI compatible.

**Comment by blaenk** [comment]
I'm observing this as well.

**Comment by deadtrickster** [comment]
Have the same issue to. Unfortunately, this repo looks abandoned :-(

**Comment by shaleh** [comment]
It appears to matter which major mode is activated. I cannot trigger it in Python or Haskell mode. I can trigger it in elisp and regular text mode.

Unlike @deadtrickster I see no missing bar at 80 chars. I just see the same misdrawn bar.

**Comment by shaleh** [comment]
It also happens in text mode so it is not purely a graphical engine issue.

I do not see the fci line on every long line either. The failed output is somewhat random.

**Comment by shaleh** [comment]
My PR resolves this issue. According to the NEWS file we have to check `display-line-numbers` and consider `line-number-display-width` in our calculations.

**Comment by joncol** [comment]
Does this need some more work? I get the following when opening up a new buffer (fill column set at 80):
![image](https://user-images.githubusercontent.com/194062/33611279-1695b378-d9ce-11e7-8f70-8929bae94208.png)

The first line contains 80 x:s so the fci-indicator is correct for that line. The second line though...

I've tried enabling `fci-mode` before `display-line-numbers-mode` and vice versa.

I'm using Emacs 26.0.90 and fci from 2017-09-05.

**Comment by alpaker** [comment]
Thanks for the report.  I couldn't reproduce exactly that result, but I could get something similar.  Does the following patch fix your issue?
```
diff --git a/fill-column-indicator.el b/fill-column-indicator.el
index 7075159..6771543 100644
--- a/fill-column-indicator.el
+++ b/fill-column-indicator.el
@@ -874,6 +874,7 @@ rough heuristic.)"
                    (= (frame-char-height) fci-char-height))))
     (fci-mode 1))
    ((not (and (= (or fci-rule-column fill-column) fci-column)
+              (= (fci-determine-padding) fci-current-lndw)
               (= tab-width fci-tab-width)))
     (fci-mode 1))
    ((and (< 0 (window-hscroll))
```

**Comment by joncol** [comment]
Hi,

@alpaker that didn't seem to make any difference. My full emacs configuration is available at https://bitbucket.org/joncol/emacs.d. Let me know if there's anything else I could do to help?

**Comment by joncol** [comment]
(Both `(fci-determine-padding)` and `fci-current-lndw` are 0 on my system.)

**Comment by alpaker** [comment]
The value of `(fci-determine-padding)` should change depending on whether `display-line-numbers` is enabled.  After applying the patch, `fci-current-lndw` should also change whenever line numbers are enabled or disabled.

Just to rule out a possible misunderstanding:  After applying the patch, you need to redefine `fci-post-command-check` (e.g., by doing `M-x eval-buffer` when visiting `fill-column-indicator.el`) and re-enable `fci-mode`.  Is that what you tried?

**Comment by alpaker** [comment]
I'm a little unsure where things stand now.  Just to be explicit, is this what you're seeing?

1. Enable fci.  line numbers off.  `fci-current-lndw` is 0.
2.  Enable line numbers.  `fci-current-lndw` is 4, but the fill-column rule does not move.

As a test:  If you change the fill column (from, say, 80 to 70) while `fci-mode` is enabled, does the display adjust automatically?

**Comment by joncol** [comment]
Can you see this?

![bug](https://user-images.githubusercontent.com/194062/33687754-65ff61be-dad9-11e7-9d69-85ba094bb9a6.gif)

**Comment by joncol** [comment]
I also tried disabling all packages other than `use-package` and `fill-column-indicator` to make sure no other package/config was interfering but my minimal config (http://sprunge.us/gGfj) resulted in the same problems.

**Comment by alpaker** [comment]
Thanks, that's helpful.  What command did you use to insert the extended string of `x`s?  I can't tell from the clip.

**Comment by joncol** [comment]
Evil-mode

**Comment by alpaker** [comment]
I haven't had a chance to look into this more, but I will over the weekend.

**Comment by alpaker** [comment]
I think I found the issue.  This [commit](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=fd3d8610b27e26107ba15070aba0d488152f8f4d) changed emacs's display engine to make the fix submitted earlier in this thread no longer necessary.  Specifically, this:  `Make :align-to count from the end of the line-number display when the offset or the width form reference that of the text area.`

Could you try this following?
```
diff --git a/fill-column-indicator.el b/fill-column-indicator.el
index 6771543..ac787b3 100644
--- a/fill-column-indicator.el
+++ b/fill-column-indicator.el
@@ -490,7 +490,7 @@ on troubleshooting.)"
 ;; fill-column.
 (defconst fci-padding-display
   '((when (not (fci-competing-overlay-p buffer-position))
-      . (space :align-to (+ fci-column fci-current-lndw)))
+      . (space :align-to fci-column))
     (space :width 0)))
```

**Comment by alpaker** [comment]
Applied against `v1.89`.

**Comment by joncol** [comment]
That did the trick! Thanks! :+1:

**Comment by alpaker** [comment]
Great.  I pushed a new version with the special handling of line number display removed.
