### ISSUE TITLE
Feature Request: Indicate multiple columns

### ISSUE THREAD

**Issue by danieljaouen** [alpaker/Fill-Column-Indicator#86]
Hello,

I'd like to be able to have the indicator display multiple columns.  Is this possible?

**Comment by alpaker** [comment]
Hi @danieljaouen.  It's definitely possible, but to be entirely honest I'm unlikely to implement it in the foreseeable future.  I've come to regard the way `fci` mode is implemented as fundamentally misguided:  It's done at too high a level in Emacs, which makes large classes of bug impossible to fix (achieving compatibility with company mode, for instance).  So I think investing much further effort in the current version of the package isn't a good use of resources.  Someday, hopefully, I or someone else will reimplement this functionality in the core of the Emacs display engine, which is the only way to do it robustly.

Sorry for the pessimism.

**Comment by danieljaouen** [comment]
No worries, I will just have to make due with the package as it is today.  Thanks for the quick reply!

**Comment by alpaker** [comment]
Hi.  Implementing multiple problems .  In
