### ISSUE TITLE
Suggestion: Rip Spacemac's FCI mode code and put it here

### ISSUE THREAD

**Issue by equwal** [alpaker/fill-column-indicator#88]
Spacemac's FCI mode works fine. Why not put that code here for people that have this in their init but don't know it is crashing their emacs?

**Comment by alpaker** [comment]
Spacemacs has some code for company-mode compatibility.  Is that what you're referring to?

**Comment by equwal** [comment]
I was thinking of the `highlight-long-lines` mode. They have your library inside spacemacs at the moment.

**Comment by alpaker** [comment]
Sorry, I don't use spacemacs, and it's not clear to me what you're requesting.
