### ISSUE TITLE
Point to new display-fill-column-indicator-mode in Emacs 27

### ISSUE THREAD

**Issue by Wojtek242** [alpaker/fill-column-indicator#90]
Hello, I used to use fci-mode occasionally and it was great that you maintained it for as long as you did. Now that you have stopped maintaining this package I was looking for some alternative since even the stale MELPA version wasn't really suitable for my needs.

Well, it turns out that a native `fill-column-indicator` has just made it into the Emacs master branch! I only found out about through a random reddit post, but here's the [link to the relevant code on master](https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/display-fill-column-indicator.el).

Perhaps, you could mention this at the top of your README? This way, people who come looking for this package will at least know that it's coming to Emacs in v27 or if they're on the master branch they can start using it straight away.

**Comment by alpaker** [comment]
Done.
